# Basic Site Settings
title: The Finley Family Website
description: "Our little corner of the internet."
# The main domain part ONLY (no subdirectory here)
url: "https://finleyfamilyman.github.io"
# The subdirectory your site lives in (starts with a slash!)
baseurl: "/MyWebsite"

# Use Georgia Font (we'll implement this fully in CSS)
font: "Georgia, serif"

# Build settings
markdown: kramdown
theme: minima # We'll override this with our custom styles, but it provides a base structure
plugins:
  - jekyll-feed

# Collections Configuration
collections:
  albums:
    output: true # Generate individual pages for each album
    sort_by: date # Sort albums by date (requires date in front matter)
    permalink: /albums/:title/ # URL structure for album pages
  recipes: # Add this new block for recipes
    output: true # Generate individual pages for each recipe
    sort_by: title # Default sort alphabetically by title
    permalink: /recipes/:title/ # URL structure like /MyWebsite/recipes/grandmas-cookies/

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
