# Basic Site Settings
title: The Finley Family Website
description: "Our little corner of the internet."
# The main domain part ONLY (no subdirectory here)
url: "https://finleyfamilyman.github.io"
# The subdirectory your site lives in (starts with a slash!)
baseurl: "/MyWebsite"

# Use Georgia Font (we'll implement this fully in CSS)
font: "Georgia, serif"

# Build settings
markdown: kramdown
theme: minima
plugins: # Use standard spaces for indentation
  - jekyll-feed
  - jekyll-archives # Indented with 2 standard spaces

# Jekyll Archives configuration (Use standard spaces for indentation)
jekyll-archives:
  enabled: # Indented with 2 standard spaces
    - tags # Indented with 4 standard spaces
  layout: tag_page # Indented with 2 standard spaces
  permalinks: # Indented with 2 standard spaces
    tag: '/recipes/tags/:name/' # Indented with 4 standard spaces

# Collections Configuration (Ensure standard spaces here too)
collections:
  albums: # Indented with 2 standard spaces
    output: true # Indented with 4 standard spaces
    sort_by: date # Indented with 4 standard spaces
    permalink: /albums/:title/ # Indented with 4 standard spaces
  recipes: # Indented with 2 standard spaces
    output: true # Indented with 4 standard spaces
    sort_by: title # Indented with 4 standard spaces
    permalink: /recipes/:title/ # Indented with 4 standard spaces

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
