# Basic Site Settings
title: The Finley Family Website
description: "Our little corner of the internet."
baseurl: "" # Keep this empty if using username.github.io repo name
url: "https://finleyfamilyman.github.io/MyWebsite/" # Replace with your site URL

# Use Georgia Font (we'll implement this fully in CSS)
font: "Georgia, serif"

# Build settings
markdown: kramdown
theme: minima # We'll override this with our custom styles, but it provides a base structure
plugins:
  - jekyll-feed

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
