# Corrected _config.yml content (using standard spaces)

# Basic Site Settings
title: The Finley Family Website
description: "Our little corner of the internet."
url: "https://finleyfamilyman.github.io" # Main domain
baseurl: "/MyWebsite" # Site subdirectory

# Use Georgia Font (we'll implement this fully in CSS)
font: "Georgia, serif"

# Build settings
markdown: kramdown
theme: minima
plugins: # Ensure correct indentation with standard spaces
  - jekyll-feed        # 2 standard spaces
  - jekyll-archives    # 2 standard spaces

# Jekyll Archives configuration (Ensure correct indentation with standard spaces)
jekyll-archives:
  enabled:             # 2 standard spaces
    - tags             # 4 standard spaces
  layout: tag_page     # 2 standard spaces
  permalinks:          # 2 standard spaces
    tag: '/recipes/tags/:name/' # 4 standard spaces

# Collections Configuration (Ensure correct indentation with standard spaces)
collections:
  albums:              # 2 standard spaces
    output: true       # 4 standard spaces
    sort_by: date      # 4 standard spaces
    permalink: /albums/:title/ # 4 standard spaces
  recipes:             # 2 standard spaces
    output: true       # 4 standard spaces
    sort_by: title     # 4 standard spaces
    permalink: /recipes/:title/ # 4 standard spaces

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
